hideOverlays = "ALL"
rgbProgress = false
blockOverlay = false
miniRender = true
enableScissor = false
type = "PROGRESS"
reloadText = "Edit in config!"
resetResources = false
reInitScreen = true
removeOverlayAtEnd = true
earlyPackStatusSend = false
doubleLoad = "FORCE_LOAD"
animationSpeed = 500.0
