hideType = "ALL"
rgbProgress = false
forceClose = false
blockOverlay = false
miniRender = true
type = "PROGRESS"
reloadText = "Edit in config!"
resetResources = false
reInitScreen = true
removeOverlayAtEnd = true
earlyPackStatusSend = false
doubleLoad = "FORCE_LOAD"
animationSpeed = 1000.0
